### ISSUE TITLE
fetchRoutes() type field does not fully work

### ISSUE THREAD

**Issue by gabeklavans** [helloitsjoe/mbta-client#43]
As in the example in the README, `mbta.fetchRoutes({type: "subway"})` works fine and only fetches Heavy Rail routes, however there is no way to get it to only fetch light rail (`tram|light rail|streetcar|trolley`) or commuter (`rail|commuter|commuter rail`). Instead it just fetches all routes, as if no type had been specified. Bus seems to work. I'm not sure why only some of these work.

Also, trying to use `route_type` filter either doesn't do anything (when trying to pass a route_type code) or crashes the app (when trying to pass a route_type string)

**Comment by helloitsjoe** [comment]
Thanks for opening this issue! I did some poking around and believe I've found the issue, but please re-open this issue if you're still having problems after updating to v1.1.8.

> Also, trying to use route_type filter either doesn't do anything (when trying to pass a route_type code)

This should be fixed with the update, and should now result in an error (see below)

> or crashes the app (when trying to pass a route_type string)

This will happen if you're using a filter the MBTA endpoint doesn't accept, e.g. using `route_type` with `fetchRoutes` (which hits `/routes`) or `type` with `fetchPredictions` (which hits `/predictions`). For example, if you try to use `route_type` with `fetchRoutes` you will get this error:

```
Error 400 fetching MBTA data: Unsupported filter(s): route_type
```

If you're not seeing an error like this, please open a new issue. I've updated the docs with a note about this. Thanks!
